### ISSUE TITLE
401 Authentication Issue with Login still

### ISSUE THREAD

**Issue by jacklmbrt07** [jacklmbrt07/merge-immersive#23]
<img width="820" alt="Screen Shot 2020-08-24 at 3 58 08 PM" src="https://user-images.githubusercontent.com/61360118/91104505-c8c74300-e622-11ea-9020-b82c0b771567.png">

When user logs in, it just redirects to homepage, and user is not logged in. Getting 401 error. We are checking the back end for an error. No alert saying "invalid credentials!" 

- We tried putting console.log(err) in each step of the controller login function, however the error is not getting logged to the console anywhere.
- We checked the bcrypt functions in our model, fixed a spelling error, but still did not solve the Issue.
- We made sure everyone was using the same code, and the whole team is having the same issue
- We read the network section of the developer tools but still could translate the source of the issue, it read the object `{ err: 'bad credentials' }`

below is our controller function for `login`

`async function login(req, res) {
  try {
    const user = await User.findOne({ email: req.body.email });
    console.log(user);
    if (!user) {
      console.log(err)
      return res.status(401).json({ err: "bad credentials" });
    }
    user.comparePassword(req.body.pw, (err, isMatch) => {
      if (isMatch) {
        const token = createJWT(user);
        res.json({ token });
      } else {
        console.log(err);
        return res.status(401).json({ err: "bad credentials" });
      }
    });
  } catch (err) {
    console.log(err);
    return res.status(401).json(err);
  }
}`

**Comment by jacklmbrt07** [comment]
the password we were using was corrupted. 

main issue was from userService.js

```function login(creds) {
  return fetch(BASE_URL + "login", {
    method: "POST",
    headers: new Headers({ "Content-Type": "application/json" }),
    body: JSON.stringify(creds),
  })
    **.then((res) => {
      if (res.ok) return res.json();
    })**
    .then(({ token }) => tokenService.setToken(token));
  // .catch((err) => console.log("userService: ", err));
}```

**Comment by myDeveloperJourney** [comment]
Steps taken to resolve this issue:

The comparePassword method defined on the Schema was incomplete, so no data was being transferred to the controller to verify the password was correct.

Also, in the userService, we weren't parsing the incoming JSON data before persisting it to localstorage
