### ISSUE TITLE
Database does not reflect the user model

### ISSUE THREAD

**Issue by HoseaCodes** [jacklmbrt07/merge-immersive#29]
# Issue: 
When a user signs up the database is only producing name, password, email, projects, hobbies, and publications from our User Schema. We cannot get it to hold the phone number, location, cohort schema, bio, githubUsername, or the githubId.

## Current Database View
![Screen Shot 2020-08-26 at 5 50 59 PM](https://user-images.githubusercontent.com/66652422/91364640-d4eb0600-e7c4-11ea-84f7-909b82d21c55.png)
## Current Model View
![Screen Shot 2020-08-26 at 5 52 34 PM](https://user-images.githubusercontent.com/66652422/91364705-fa780f80-e7c4-11ea-8fd3-e74aeacb9869.png)

## What we attempted:

We deleted old profiles and attempted to sign up for a new user.

## Goal:
To have the User Schema and database mirror each other.

**Comment by jacklmbrt07** [comment]
Should cohortSchema even need to be in another Schema, we are not ever manipulating that data seperately

**Comment by HoseaCodes** [comment]
Updated the controller function
